Added WIP UInt8 packet support in Cluster.
Implement partial support for MOVE_TIME_SKIPPED OpCode.
First step towards fixing BattleGrounds.

As of the moment you cannot teleport into the BG due to a packet error referenced below.

Opcode handler CMSG_BATTLEFIELD_PORT:000002D5 caused an error:
System.ArgumentException: Destination array is not long enough to copy all the i
tems in the collection. Check array index and length.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at WorldCluster.WC_Handlers_Battleground.On_CMSG_BATTLEFIELD_PORT(PacketClass
& packet, ClientClass& client) in C:\Users\Krill\Desktop\serverZero-master\Serve
r\WorldCluster\Handlers\WC.Handlers.Battleground.vb:line 30